version: '3'
services:
  tox:
    image: gitmachete/ci-tox:git${GIT_VERSION}-python${PYTHON_VERSION}-${DIRECTORY_HASH:-unspecified}
#    user: ${UID}:${GID}
#    working_dir: $HOME
#    stdin_open: true
    build:
      context: build-context
      dockerfile: ../Dockerfile # relative to build-context
      args:
        - git_version=${GIT_VERSION:-0.0.0}
        - python_version=${PYTHON_VERSION:-0.0.0}
    environment:
      - BUILD_DOCS=${BUILD_DOCS:-false}
      - CHECK_COVERAGE=${CHECK_COVERAGE:-false}
      - CHECK_PEP8=${CHECK_PEP8:-false}
#      - GID={GID}
#      - UID={UID}
    volumes:
      # Host path is relative to current directory, not build-context
      - ../..:/home/ci_user/git-machete
#      - /etc/group:/etc/group:ro
#      - /etc/passwd:/etc/passwd:ro
#      - /etc/shadow:/etc/shadow:ro
#    tty: true
#    command: tail -f /dev/null
